version: '3.5'

services:
  frontend:
    container_name: frontend
    build: ./
    volumes:
    - './:/usr/src/app'
    ports:
    - "4200:4200"
    command: >
      bash -c "npm start"
  docker-nginx:
    container_name: docker-nginx
    build: ./
    ports:
    - "80:80"
    command: ["nginx", "-g", "daemon off;"]
    links:
      - frontend

